In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("✅ Libraries Imported Successfully")

✅ Libraries Imported Successfully

In [2]:
DATA_PATH = Path("../../Dataset/raw/brazillian Ecommerce dataset")

print(DATA_PATH)

../../Dataset/raw/brazillian Ecommerce dataset

In [3]:
customers = pd.read_csv(DATA_PATH / "olist_customers_dataset.csv")
orders = pd.read_csv(DATA_PATH / "olist_orders_dataset.csv")
order_items = pd.read_csv(DATA_PATH / "olist_order_items_dataset.csv")
payments = pd.read_csv(DATA_PATH / "olist_order_payments_dataset.csv")
reviews = pd.read_csv(DATA_PATH / "olist_order_reviews_dataset.csv")
products = pd.read_csv(DATA_PATH / "olist_products_dataset.csv")
sellers = pd.read_csv(DATA_PATH / "olist_sellers_dataset.csv")
geolocation = pd.read_csv(DATA_PATH / "olist_geolocation_dataset.csv")
category_translation = pd.read_csv(
    DATA_PATH / "product_category_name_translation.csv"
)

print("✅ All datasets loaded successfully!")

✅ All datasets loaded successfully!

In [4]:
datasets = {
    "Customers": customers,
    "Orders": orders,
    "Order Items": order_items,
    "Payments": payments,
    "Reviews": reviews,
    "Products": products,
    "Sellers": sellers,
    "Geolocation": geolocation,
    "Category Translation": category_translation,
}

for name, df in datasets.items():
    print(f"{name:<22} {df.shape}")

Customers              (99441, 5)
Orders                 (99441, 8)
Order Items            (112650, 7)
Payments               (103886, 5)
Reviews                (99224, 7)
Products               (32951, 9)
Sellers                (3095, 4)
Geolocation            (1000163, 5)
Category Translation   (71, 2)

In [5]:
for name, df in datasets.items():
    print("=" * 80)
    print(f"📂 {name}")
    print("=" * 80)

    display(df.head())

    print("\nShape :", df.shape)
    print("\nColumns :")
    print(df.columns.tolist())

    print("\nData Types :")
    print(df.dtypes)

    print("\n")

================================================================================
📂 Customers
================================================================================

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

Shape : (99441, 5)

Columns :
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

Data Types :
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object


================================================================================
📂 Orders
================================================================================

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

Shape : (99441, 8)

Columns :
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

Data Types :
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object


================================================================================
📂 Order Items
================================================================================

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

Shape : (112650, 7)

Columns :
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

Data Types :
order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object


================================================================================
📂 Payments
================================================================================

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

Shape : (103886, 5)

Columns :
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

Data Types :
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object


================================================================================
📂 Reviews
================================================================================

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

Shape : (99224, 7)

Columns :
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

Data Types :
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object


================================================================================
📂 Products
================================================================================

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

Shape : (32951, 9)

Columns :
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

Data Types :
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object


================================================================================
📂 Sellers
================================================================================

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

Shape : (3095, 4)

Columns :
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

Data Types :
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object


================================================================================
📂 Geolocation
================================================================================

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

Shape : (1000163, 5)

Columns :
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

Data Types :
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object


================================================================================
📂 Category Translation
================================================================================

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

Shape : (71, 2)

Columns :
['product_category_name', 'product_category_name_english']

Data Types :
product_category_name            object
product_category_name_english    object
dtype: object

In [6]:
missing_summary = {}

for name, df in datasets.items():
    missing = df.isnull().sum()
    missing = missing[missing > 0].sort_values(ascending=False)

    if len(missing) > 0:
        missing_summary[name] = missing

for dataset, values in missing_summary.items():
    print("=" * 70)
    print(dataset)
    print("=" * 70)
    print(values)
    print()

======================================================================
Orders
======================================================================
order_delivered_customer_date    2965
order_delivered_carrier_date     1783
order_approved_at                 160
dtype: int64

======================================================================
Reviews
======================================================================
review_comment_title      87656
review_comment_message    58247
dtype: int64

======================================================================
Products
======================================================================
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [7]:
for name, df in datasets.items():
    duplicates = df.duplicated().sum()
    print(f"{name:<25} : {duplicates}")

Customers                 : 0
Orders                    : 0
Order Items               : 0
Payments                  : 0
Reviews                   : 0
Products                  : 0
Sellers                   : 0
Geolocation               : 261831
Category Translation      : 0

In [8]:
for name, df in datasets.items():
    memory = df.memory_usage(deep=True).sum() / (1024**2)
    print(f"{name:<25}: {memory:.2f} MB")

Customers                : 26.59 MB
Orders                   : 52.94 MB
Order Items              : 35.99 MB
Payments                 : 16.23 MB
Reviews                  : 39.12 MB
Products                 : 6.30 MB
Sellers                  : 0.59 MB
Geolocation              : 130.26 MB
Category Translation     : 0.01 MB

In [9]:
for name, df in datasets.items():

    print("="*80)
    print(name)
    print("="*80)

    missing = (df.isnull().sum()/len(df))*100
    missing = missing[missing>0].sort_values(ascending=False)

    if len(missing)==0:
        print("No Missing Values ✅")
    else:
        print(missing.round(2))

    print()

================================================================================
Customers
================================================================================
No Missing Values ✅

================================================================================
Orders
================================================================================
order_delivered_customer_date    2.98
order_delivered_carrier_date     1.79
order_approved_at                0.16
dtype: float64

================================================================================
Order Items
================================================================================
No Missing Values ✅

================================================================================
Payments
================================================================================
No Missing Values ✅

================================================================================
Reviews
================================================================================
review_comment_title      88.34
review_comment_message    58.70
dtype: float64

================================================================================
Products
================================================================================
product_category_name         1.85
product_name_lenght           1.85
product_description_lenght    1.85
product_photos_qty            1.85
product_weight_g              0.01
product_length_cm             0.01
product_height_cm             0.01
product_width_cm              0.01
dtype: float64

================================================================================
Sellers
================================================================================
No Missing Values ✅

================================================================================
Geolocation
================================================================================
No Missing Values ✅

================================================================================
Category Translation
================================================================================
No Missing Values ✅

In [10]:
cleaned_datasets = {}

for name, df in datasets.items():

    before = len(df)

    df = df.drop_duplicates()

    after = len(df)

    print(f"{name:<22} Removed {before-after} duplicate rows")

    cleaned_datasets[name] = df

Customers              Removed 0 duplicate rows
Orders                 Removed 0 duplicate rows
Order Items            Removed 0 duplicate rows
Payments               Removed 0 duplicate rows
Reviews                Removed 0 duplicate rows
Products               Removed 0 duplicate rows
Sellers                Removed 0 duplicate rows
Geolocation            Removed 261831 duplicate rows
Category Translation   Removed 0 duplicate rows

In [11]:
orders = cleaned_datasets["Orders"]

date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

print(orders.dtypes)

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [12]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [13]:
orders["order_approved_at"] = orders["order_approved_at"].fillna(
    orders["order_purchase_timestamp"]
)

orders["order_delivered_carrier_date"] = orders[
    "order_delivered_carrier_date"
].fillna(method="ffill")

orders["order_delivered_customer_date"] = orders[
    "order_delivered_customer_date"
].fillna(method="ffill")

print("Missing values handled ✅")

Missing values handled ✅

/var/folders/zh/26k923fn4wbfjn1nq443pqkm0000gn/T/ipykernel_20579/444470671.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ].fillna(method="ffill")
/var/folders/zh/26k923fn4wbfjn1nq443pqkm0000gn/T/ipykernel_20579/444470671.py:11: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ].fillna(method="ffill")

In [14]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99441 non-null  datetime64[ns]
 5   order_delivered_carrier_date   99441 non-null  datetime64[ns]
 6   order_delivered_customer_date  99441 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [15]:
orders["Purchase Year"] = orders["order_purchase_timestamp"].dt.year
orders["Purchase Month"] = orders["order_purchase_timestamp"].dt.month
orders["Purchase Day"] = orders["order_purchase_timestamp"].dt.day
orders["Purchase Weekday"] = orders["order_purchase_timestamp"].dt.day_name()

orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,Purchase Year,Purchase Month,Purchase Day,Purchase Weekday
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2017,10,2,Monday
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,2018,7,24,Tuesday
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,2018,8,8,Wednesday
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,2017,11,18,Saturday
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2018,2,13,Tuesday

In [16]:
orders["Delivery Days"] = (
    orders["order_delivered_customer_date"] -
    orders["order_purchase_timestamp"]
).dt.days

orders[["Delivery Days"]].describe()

       Delivery Days
count   99441.000000
mean       13.798373
std        40.947699
min      -553.000000
25%         6.000000
50%        10.000000
75%        16.000000
max       692.000000

In [17]:
orders.to_csv(
    "../../Dataset/processed/orders_cleaned.csv",
    index=False
)

print("Orders dataset saved successfully ✅")

Orders dataset saved successfully ✅

In [18]:
invalid_delivery = orders[orders["Delivery Days"] < 0]

print("Invalid Orders :", len(invalid_delivery))

invalid_delivery.head()

Invalid Orders : 1209

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,Purchase Year,Purchase Month,Purchase Day,Purchase Weekday,Delivery Days
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,2017-07-18 12:34:04,2017-07-21 19:59:36,2017-10-03,2017,9,3,Sunday,-44
154,6942b8da583c2f9957e990d028607019,52006a9383bf149a4fb24226b173106f,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,2017-05-12 12:04:38,2018-02-07,2018,1,10,Wednesday,-243
299,3b4ad687e7e5190db827e1ae5a8989dd,1a87b8517b7d31373b50396eb15cb445,shipped,2018-06-28 12:52:15,2018-06-28 13:11:09,2018-07-04 15:20:00,2018-04-09 19:26:42,2018-08-03,2018,6,28,Thursday,-80
305,b68d69564a79dea4776afa33d1d2fcab,de1e5517fb50896bbdcff5814fb31802,shipped,2018-02-28 08:57:03,2018-02-28 10:40:35,2018-03-05 16:10:13,2017-10-03 18:35:37,2018-03-23,2018,2,28,Wednesday,-148
374,5869074071e0f56e9085dc3742c97b2a,7203eb38fea2b4a15dd6c39575314aa4,shipped,2018-06-08 20:06:48,2018-06-12 04:35:37,2018-06-12 14:09:00,2018-06-05 20:32:10,2018-06-28,2018,6,8,Friday,-3

In [19]:
orders = orders[orders["Delivery Days"] >= 0]

print("Remaining Orders :", len(orders))

Remaining Orders : 98232

In [20]:
orders["order_status"].value_counts()

order_status
delivered      96471
shipped          604
unavailable      423
canceled         311
processing       212
invoiced         205
created            4
approved           2
Name: count, dtype: int64

In [21]:
orders.isnull().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
Purchase Year                    0
Purchase Month                   0
Purchase Day                     0
Purchase Weekday                 0
Delivery Days                    0
dtype: int64

In [22]:
orders.describe(include="all")

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,Purchase Year,Purchase Month,Purchase Day,Purchase Weekday,Delivery Days
count,98232,98232,98232,98232,98232,98232,98232,98232,98232.000000,98232.000000,98232.000000,98232,98232.000000
unique,98232,98232,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,NaN
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Monday,NaN
freq,1,1,96471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15987,NaN
mean,NaN,NaN,NaN,2017-12-30 13:04:22.725344256,2017-12-30 23:27:17.088596224,2018-01-05 06:06:51.487193344,2018-01-15 18:08:31.452734464,2018-01-23 07:58:33.804056064,2017.537686,6.031008,15.509661,NaN,15.746956
min,NaN,NaN,NaN,2016-09-04 21:15:19,2016-09-15 12:16:38,2016-10-08 10:34:01,2016-10-11 13:46:32,2016-09-30 00:00:00,2016.000000,1.000000,1.000000,NaN,0.000000
25%,NaN,NaN,NaN,2017-09-11 14:15:11.249999872,2017-09-11 23:25:17,2017-09-18 16:21:37,2017-09-27 17:40:39.249999872,2017-10-02 00:00:00,2017.000000,3.000000,8.000000,NaN,6.000000
50%,NaN,NaN,NaN,2018-01-18 09:11:54,2018-01-18 13:12:59,2018-01-24 18:21:33.500000,2018-02-05 18:07:57.500000,2018-02-14 00:00:00,2018.000000,6.000000,15.000000,NaN,10.000000
75%,NaN,NaN,NaN,2018-05-04 08:40:40.500000,2018-05-04 15:10:22,2018-05-08 14:38:00,2018-05-16 19:16:47,2018-05-25 00:00:00,2018.000000,8.000000,23.000000,NaN,16.000000
max,NaN,NaN,NaN,2018-08-29 15:00:37,2018-08-29 15:10:26,2018-09-11 19:48:28,2018-10-17 13:22:46,2018-10-25 00:00:00,2018.000000,12.000000,31.000000,NaN,692.000000
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.505253,3.232126,8.666395,NaN,35.030407

In [23]:
orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
Purchase Year                             int32
Purchase Month                            int32
Purchase Day                              int32
Purchase Weekday                         object
Delivery Days                             int64
dtype: object

In [24]:
orders.to_csv(
    "../../Dataset/processed/orders_final_cleaned.csv",
    index=False
)

print("✅ Final cleaned dataset saved successfully!")

✅ Final cleaned dataset saved successfully!