In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("✅ Libraries Imported Successfully")

✅ Libraries Imported Successfully

In [2]:
DATA_PATH = Path("../../Dataset/raw/brazillian Ecommerce dataset")

print(DATA_PATH)

../../Dataset/raw/brazillian Ecommerce dataset

In [3]:
customers = pd.read_csv(DATA_PATH / "olist_customers_dataset.csv")

order_items = pd.read_csv(DATA_PATH / "olist_order_items_dataset.csv")

payments = pd.read_csv(DATA_PATH / "olist_order_payments_dataset.csv")

products = pd.read_csv(DATA_PATH / "olist_products_dataset.csv")

reviews = pd.read_csv(DATA_PATH / "olist_order_reviews_dataset.csv")

sellers = pd.read_csv(DATA_PATH / "olist_sellers_dataset.csv")

geolocation = pd.read_csv(DATA_PATH / "olist_geolocation_dataset.csv")

category_translation = pd.read_csv(
    DATA_PATH / "product_category_name_translation.csv"
)

print("✅ All datasets loaded successfully!")

✅ All datasets loaded successfully!

In [4]:
datasets = {
    "Customers": customers,
    "Order Items": order_items,
    "Payments": payments,
    "Products": products,
    "Reviews": reviews,
    "Sellers": sellers,
    "Geolocation": geolocation,
    "Category Translation": category_translation,
}

for name, df in datasets.items():
    print(f"{name:<22} {df.shape}")

Customers              (99441, 5)
Order Items            (112650, 7)
Payments               (103886, 5)
Products               (32951, 9)
Reviews                (99224, 7)
Sellers                (3095, 4)
Geolocation            (1000163, 5)
Category Translation   (71, 2)

In [5]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [6]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [7]:
print("Duplicate Rows :", customers.duplicated().sum())

Duplicate Rows : 0

In [8]:
customers = customers.drop_duplicates()

print("Shape after removing duplicates:")
print(customers.shape)

Shape after removing duplicates:
(99441, 5)

In [9]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [10]:
customers.describe(include="all")

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
count,99441,99441,99441.000000,99441,99441
unique,99441,96096,NaN,4119,27
top,06b8999e2fba1a1fbc88172c00ba8bc7,8d50f5eadf50201ccdcedfb9e2ac8455,NaN,sao paulo,SP
freq,1,17,NaN,15540,41746
mean,NaN,NaN,35137.474583,NaN,NaN
std,NaN,NaN,29797.938996,NaN,NaN
min,NaN,NaN,1003.000000,NaN,NaN
25%,NaN,NaN,11347.000000,NaN,NaN
50%,NaN,NaN,24416.000000,NaN,NaN
75%,NaN,NaN,58900.000000,NaN,NaN
max,NaN,NaN,99990.000000,NaN,NaN

In [11]:
customers.dtypes

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

In [12]:
customers["customer_state"].value_counts()

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: count, dtype: int64

In [13]:
customers["customer_city"].nunique()

4119

In [14]:
print(customers.shape)

(99441, 5)

In [15]:
customers.to_csv(
    "../../Dataset/processed/customers.csv",
    index=False
)

print("✅ customers.csv saved successfully!")

✅ customers.csv saved successfully!

In [16]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [17]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [18]:
print("Duplicate Rows :", order_items.duplicated().sum())

Duplicate Rows : 0

In [19]:
order_items = order_items.drop_duplicates()

print(order_items.shape)

(112650, 7)

In [20]:
order_items.describe(include="all")

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
count,112650,112650.000000,112650,112650,112650,112650.000000,112650.000000
unique,98666,NaN,32951,3095,93318,NaN,NaN
top,8272b63d03f5f79c56e9e4120aec44ef,NaN,aca2eb7d00ea1a7b8ebd4e68314663af,6560211a19b47992c3666cc44a7e94c0,2017-07-21 18:25:23,NaN,NaN
freq,21,NaN,527,2033,21,NaN,NaN
mean,NaN,1.197834,NaN,NaN,NaN,120.653739,19.990320
std,NaN,0.705124,NaN,NaN,NaN,183.633928,15.806405
min,NaN,1.000000,NaN,NaN,NaN,0.850000,0.000000
25%,NaN,1.000000,NaN,NaN,NaN,39.900000,13.080000
50%,NaN,1.000000,NaN,NaN,NaN,74.990000,16.260000
75%,NaN,1.000000,NaN,NaN,NaN,134.900000,21.150000
max,NaN,21.000000,NaN,NaN,NaN,6735.000000,409.680000

In [21]:
order_items.dtypes

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

In [22]:
order_items["price"].describe()

count    112650.000000
mean        120.653739
std         183.633928
min           0.850000
25%          39.900000
50%          74.990000
75%         134.900000
max        6735.000000
Name: price, dtype: float64

In [23]:
order_items["freight_value"].describe()

count    112650.000000
mean         19.990320
std          15.806405
min           0.000000
25%          13.080000
50%          16.260000
75%          21.150000
max         409.680000
Name: freight_value, dtype: float64

In [24]:
print(order_items.shape)

(112650, 7)

In [25]:
order_items.to_csv(
    "../../Dataset/processed/order_items.csv",
    index=False
)

print("✅ order_items.csv saved successfully!")

✅ order_items.csv saved successfully!

In [26]:
payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [27]:
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [28]:
print("Duplicate Rows :", payments.duplicated().sum())

Duplicate Rows : 0

In [29]:
payments = payments.drop_duplicates()

print(payments.shape)

(103886, 5)

In [30]:
payments.describe(include="all")

,order_id,payment_sequential,payment_type,payment_installments,payment_value
count,103886,103886.000000,103886,103886.000000,103886.000000
unique,99440,NaN,5,NaN,NaN
top,fa65dad1b0e818e3ccc5cb0e39231352,NaN,credit_card,NaN,NaN
freq,29,NaN,76795,NaN,NaN
mean,NaN,1.092679,NaN,2.853349,154.100380
std,NaN,0.706584,NaN,2.687051,217.494064
min,NaN,1.000000,NaN,0.000000,0.000000
25%,NaN,1.000000,NaN,1.000000,56.790000
50%,NaN,1.000000,NaN,1.000000,100.000000
75%,NaN,1.000000,NaN,4.000000,171.837500
max,NaN,29.000000,NaN,24.000000,13664.080000

In [31]:
payments.dtypes

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

In [32]:
payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [33]:
payments["payment_value"].describe()

count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64

In [34]:
payments["payment_installments"].describe()

count    103886.000000
mean          2.853349
std           2.687051
min           0.000000
25%           1.000000
50%           1.000000
75%           4.000000
max          24.000000
Name: payment_installments, dtype: float64

In [35]:
payments.to_csv(
    "../../Dataset/processed/payments.csv",
    index=False
)

print("✅ payments.csv saved successfully!")

✅ payments.csv saved successfully!

In [36]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [37]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [38]:
print("Duplicate Rows :", products.duplicated().sum())

Duplicate Rows : 0

In [39]:
products = products.drop_duplicates()

print(products.shape)

(32951, 9)

In [40]:
products["product_category_name"] = products[
    "product_category_name"
].fillna("Unknown")

print("Category missing values handled ✅")

Category missing values handled ✅

In [42]:
products["product_name_lenght"] = products[
    "product_name_lenght"
].fillna(products["product_name_lenght"].median())

In [43]:
products["product_description_lenght"] = products[
    "product_description_lenght"
].fillna(products["product_description_lenght"].median())

In [44]:
products["product_photos_qty"] = products[
    "product_photos_qty"
].fillna(products["product_photos_qty"].median())

In [45]:
products.describe(include="all")

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32951,32951,32951.000000,32951.000000,32951.000000,32949.000000,32949.000000,32949.000000,32949.000000
unique,32951,74,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,1e9e8ef04dbcff4541ed26657ea517e5,cama_mesa_banho,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,3029,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,48.523656,768.227945,2.166975,2276.472488,30.815078,16.937661,23.196728
std,NaN,NaN,10.156155,629.658469,1.728063,4282.038731,16.914458,13.637554,12.079047
min,NaN,NaN,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,NaN,NaN,42.000000,344.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,NaN,NaN,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,NaN,NaN,57.000000,961.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,NaN,NaN,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [46]:
products.to_csv(
    "../../Dataset/processed/products.csv",
    index=False
)

print("✅ products.csv saved successfully!")

✅ products.csv saved successfully!

In [47]:
products.to_csv(
    "../../Dataset/processed/products.csv",
    index=False
)

print("✅ products.csv saved successfully!")

✅ products.csv saved successfully!

In [48]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [49]:
reviews.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [51]:
print("Duplicate Rows :", reviews.duplicated().sum())

Duplicate Rows : 0

In [52]:
reviews = reviews.drop_duplicates()

print(reviews.shape)

(99224, 7)

In [53]:
reviews["review_creation_date"] = pd.to_datetime(
    reviews["review_creation_date"]
)

reviews["review_answer_timestamp"] = pd.to_datetime(
    reviews["review_answer_timestamp"]
)

print("✅ Date columns converted")

✅ Date columns converted

In [54]:
reviews["review_score"].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [55]:
reviews.describe(include="all")

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
count,99224,99224,99224.000000,11568,40977,99224,99224
unique,98410,98673,NaN,4527,36159,NaN,NaN
top,7b606b0d57b078384f0b58eac1d41d78,c88b1d1b157a9999ce368f218a407141,NaN,Recomendo,Muito bom,NaN,NaN
freq,3,3,NaN,423,230,NaN,NaN
mean,NaN,NaN,4.086421,NaN,NaN,2018-01-12 20:49:23.948238336,2018-01-16 00:23:56.977938688
min,NaN,NaN,1.000000,NaN,NaN,2016-10-02 00:00:00,2016-10-07 18:32:28
25%,NaN,NaN,4.000000,NaN,NaN,2017-09-23 00:00:00,2017-09-27 01:53:27.249999872
50%,NaN,NaN,5.000000,NaN,NaN,2018-02-02 00:00:00,2018-02-04 22:41:47.500000
75%,NaN,NaN,5.000000,NaN,NaN,2018-05-16 00:00:00,2018-05-20 12:11:21.500000
max,NaN,NaN,5.000000,NaN,NaN,2018-08-31 00:00:00,2018-10-29 12:27:35
std,NaN,NaN,1.347579,NaN,NaN,NaN,NaN

In [56]:
reviews.dtypes

review_id                          object
order_id                           object
review_score                        int64
review_comment_title               object
review_comment_message             object
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

In [57]:
reviews.to_csv(
    "../../Dataset/processed/reviews.csv",
    index=False
)

print("✅ reviews.csv saved successfully!")

✅ reviews.csv saved successfully!

In [58]:
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [59]:
sellers.isnull().sum()

seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

In [60]:
print("Duplicate Rows :", sellers.duplicated().sum())

Duplicate Rows : 0

In [61]:
sellers = sellers.drop_duplicates()

print(sellers.shape)

(3095, 4)

In [62]:
sellers.describe(include="all")

,seller_id,seller_zip_code_prefix,seller_city,seller_state
count,3095,3095.000000,3095,3095
unique,3095,NaN,611,23
top,3442f8959a84dea7ee197c632cb2df15,NaN,sao paulo,SP
freq,1,NaN,694,1849
mean,NaN,32291.059451,NaN,NaN
std,NaN,32713.453830,NaN,NaN
min,NaN,1001.000000,NaN,NaN
25%,NaN,7093.500000,NaN,NaN
50%,NaN,14940.000000,NaN,NaN
75%,NaN,64552.500000,NaN,NaN
max,NaN,99730.000000,NaN,NaN

In [63]:
sellers.dtypes

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

In [64]:
sellers["seller_state"].value_counts()

seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
RN       5
MS       5
MT       4
RO       2
SE       2
PI       1
AC       1
MA       1
AM       1
PA       1
Name: count, dtype: int64

In [65]:
print("Unique Cities :", sellers["seller_city"].nunique())

Unique Cities : 611

In [66]:
print(sellers.shape)

(3095, 4)

In [67]:
sellers.to_csv(
    "../../Dataset/processed/sellers.csv",
    index=False
)

print("✅ sellers.csv saved successfully!")

✅ sellers.csv saved successfully!

In [68]:
geolocation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [69]:
geolocation.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [70]:
print("Duplicate Rows :", geolocation.duplicated().sum())

Duplicate Rows : 261831

In [71]:
geolocation = geolocation.drop_duplicates()

print(geolocation.shape)

(738332, 5)

In [72]:
geolocation.describe(include="all")

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
count,738332.000000,738332.000000,738332.000000,738332,738332
unique,NaN,NaN,NaN,8011,27
top,NaN,NaN,NaN,sao paulo,SP
freq,NaN,NaN,NaN,79927,285976
mean,38316.086800,-20.998353,-46.461098,NaN,NaN
std,30632.496675,5.892315,4.393705,NaN,NaN
min,1001.000000,-36.605374,-101.466766,NaN,NaN
25%,12600.000000,-23.603061,-48.867822,NaN,NaN
50%,29144.000000,-22.873588,-46.647278,NaN,NaN
75%,65950.000000,-19.923336,-43.836974,NaN,NaN
max,99990.000000,45.065933,121.105394,NaN,NaN

In [73]:
geolocation.dtypes

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

In [74]:
geolocation["geolocation_state"].value_counts()

geolocation_state
SP    285976
MG    101353
RJ     78836
RS     48093
PR     45059
SC     30191
BA     27720
GO     15601
PE     13162
ES     12632
CE      9541
MT      9374
DF      9080
MS      8594
PA      8551
MA      6277
PB      4787
RN      4014
PI      3592
AL      3415
TO      2977
SE      2653
RO      2523
AM      1986
AC      1039
AP       738
RR       568
Name: count, dtype: int64

In [75]:
print("Latitude Range")
print(geolocation["geolocation_lat"].describe())

print("\nLongitude Range")
print(geolocation["geolocation_lng"].describe())

Latitude Range
count    738332.000000
mean        -20.998353
std           5.892315
min         -36.605374
25%         -23.603061
50%         -22.873588
75%         -19.923336
max          45.065933
Name: geolocation_lat, dtype: float64

Longitude Range
count    738332.000000
mean        -46.461098
std           4.393705
min        -101.466766
25%         -48.867822
50%         -46.647278
75%         -43.836974
max         121.105394
Name: geolocation_lng, dtype: float64

In [76]:
print(geolocation.shape)

(738332, 5)

In [77]:
geolocation.to_csv(
    "../../Dataset/processed/geolocation.csv",
    index=False
)

print("✅ geolocation.csv saved successfully!")

✅ geolocation.csv saved successfully!

In [2]:
import pandas as pd

category_translation = pd.read_csv(
    "../../Dataset/raw/brazillian Ecommerce dataset/product_category_name_translation.csv"
)

print(category_translation.shape)

(71, 2)

In [3]:
category_translation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [2]:
import pandas as pd

category_translation = pd.read_csv(
    "../../Dataset/raw/brazillian Ecommerce dataset/product_category_name_translation.csv"
)

print(category_translation.shape)

(71, 2)

In [3]:
category_translation.isnull().sum()

product_category_name            0
product_category_name_english    0
dtype: int64

In [4]:
category_translation.describe(include="all")

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [5]:
category_translation.to_csv(
    "../../Dataset/processed/category_translation.csv",
    index=False
)

print("✅ category_translation.csv saved successfully!")

✅ category_translation.csv saved successfully!

In [6]:
import os

print(os.path.exists("../../Dataset/processed/category_translation.csv"))

True

In [7]:
from pathlib import Path

processed_path = Path("../../Dataset/processed")

for file in sorted(processed_path.glob("*.csv")):
    print(file.name)

category_translation.csv
customers.csv
geolocation.csv
order_items.csv
orders_cleaned.csv
orders_eda.csv
orders_final_cleaned.csv
payments.csv
products.csv
reviews.csv
sellers.csv

In [8]:
customers = pd.read_csv(processed_path / "customers.csv")
order_items = pd.read_csv(processed_path / "order_items.csv")
payments = pd.read_csv(processed_path / "payments.csv")
products = pd.read_csv(processed_path / "products.csv")
reviews = pd.read_csv(processed_path / "reviews.csv")
sellers = pd.read_csv(processed_path / "sellers.csv")
geolocation = pd.read_csv(processed_path / "geolocation.csv")
category_translation = pd.read_csv(processed_path / "category_translation.csv")

print("✅ All processed datasets loaded successfully!")

✅ All processed datasets loaded successfully!

In [9]:
datasets = {
    "Customers": customers,
    "Order Items": order_items,
    "Payments": payments,
    "Products": products,
    "Reviews": reviews,
    "Sellers": sellers,
    "Geolocation": geolocation,
    "Category Translation": category_translation,
}

for name, df in datasets.items():
    print(f"{name:<22} {df.shape}")

Customers              (99441, 5)
Order Items            (112650, 7)
Payments               (103886, 5)
Products               (32951, 9)
Reviews                (99224, 7)
Sellers                (3095, 4)
Geolocation            (738332, 5)
Category Translation   (71, 2)

In [10]:
for name, df in datasets.items():
    print("\n", "=" * 50)
    print(name)
    print(df.isnull().sum())

 ==================================================
Customers
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

 ==================================================
Order Items
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

 ==================================================
Payments
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

 ==================================================
Products
product_id                    0
product_category_name         0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              2
product_length_cm             2
product_height_cm             2
product_width_cm              2
dtype: int64

 ==================================================
Reviews
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

 ==================================================
Sellers
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

 ==================================================
Geolocation
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

 ==================================================
Category Translation
product_category_name            0
product_category_name_english    0
dtype: int64

In [11]:
print("=" * 60)
print("🎉 ALL DATASETS CLEANED SUCCESSFULLY")
print("📂 Saved in Dataset/processed/")
print("🚀 Ready for SQL Analysis")
print("=" * 60)

============================================================
🎉 ALL DATASETS CLEANED SUCCESSFULLY
📂 Saved in Dataset/processed/
🚀 Ready for SQL Analysis
============================================================